# Generated by Django 4.1.4 on 2023-02-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_animal_name_alter_animal_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='image',
            field=models.ImageField(default='d.png', upload_to='img_data/'),
        ),
    ]
