# Generated by Django 4.1.4 on 2023-02-26 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_animal_species_delete_species'),
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='species',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.species'),
            preserve_default=False,
        ),
    ]
